nodeLinker: node-modules

# Satisfy/silence common transitive peer warnings
packageExtensions:
  "@chromatic-com/storybook@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true

  "@storybook/core@*":
    peerDependencies:
      storybook: "*"
    peerDependenciesMeta:
      storybook:
        optional: true

  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true

  "babel-plugin-styled-components@*":
    peerDependencies:
      "@babel/core": "*"

  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true

  "styled-components@*":
    peerDependencies:
      "@babel/core": "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true