nodeLinker: node-modules

# Satisfy/silence common transitive peer warnings
packageExtensions:
  '@chromatic-com/storybook@*':
    peerDependencies:
      react: '*'

  '@storybook/core@*':
    peerDependencies:
      storybook: '*'

  '@storybook/addon-docs@*':
    peerDependencies:
      '@types/react': '*'

  'babel-plugin-styled-components@*':
    peerDependencies:
      '@babel/core': '*'

  '@storybook/addon-essentials@*':
    peerDependencies:
      '@types/react': '*'

  'styled-components@*':
    peerDependencies:
      '@babel/core': '*'

  'eslint-plugin-storybook@*':
    peerDependencies:
      typescript: '*'
